github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: 4Xsample
ko_fi: 4Xsample # Replace with a single Ko-fi username
custom: 'https://www.paypal.com/donate/?hosted_button_id=EFVMSRHVBNJP4' # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']